/* ============================================================
   GnanaBarani Furnitures — Product Catalog Data
   63 real products from actual shop images
   ============================================================ */

const CATEGORIES = [
  { id: 'sofa',       label: 'Sofas & Diwans',    icon: 'fa-couch' },
  { id: 'bed',        label: 'Beds',               icon: 'fa-bed' },
  { id: 'dining',     label: 'Dining Tables',      icon: 'fa-utensils' },
  { id: 'chair',      label: 'Chairs',             icon: 'fa-chair' },
  { id: 'wardrobe',   label: 'Wardrobes',          icon: 'fa-door-closed' },
  { id: 'door',       label: 'Doors',              icon: 'fa-archway' },
  { id: 'window',     label: 'Windows',            icon: 'fa-border-all' },
  { id: 'decorative', label: 'Home Decoratives',   icon: 'fa-paint-brush' },
  { id: 'statue',     label: 'Statues',            icon: 'fa-torii-gate' },
  { id: 'kitchen',    label: 'Kitchen Utensils',   icon: 'fa-bowl-food' },
  { id: 'cradle',     label: 'Baby Cradle & Swings', icon: 'fa-baby-carriage' },
  { id: 'pooja',      label: 'Pooja Items',        icon: 'fa-fire-flame-curved' },
];

const PRODUCTS = [
  /* ────────────── SOFAS & DIWANS ────────────── */
  {
    id: 1,
    name: 'Classic Teak Diwan – Light Finish',
    category: 'sofa',
    price: 28000,
    material: 'Teak Wood',
    description: 'A beautifully crafted teak diwan with spindle railings and polished light finish. Perfect for living rooms and verandahs, offering both seating and daybed functionality.',
    dimensions: 'L: 195cm  W: 75cm  H: 95cm',
    warranty: '2 Years',
    image: 'images/IMG-20250924-WA0002.jpg',
    rating: 4.5,
    featured: true
  },
  {
    id: 2,
    name: 'Royal Rosewood Carved Diwan',
    category: 'sofa',
    price: 38000,
    material: 'Rosewood',
    description: 'Handcrafted rosewood diwan with intricate spindle back and decorative brass medallions on the sides. Deep mahogany finish that adds regal charm to any room.',
    dimensions: 'L: 200cm  W: 78cm  H: 98cm',
    warranty: '3 Years',
    image: 'images/IMG-20250924-WA0003.jpg',
    rating: 4.8,
    featured: true
  },
  {
    id: 3,
    name: 'Carved Teak Settee – Slatted Seat',
    category: 'sofa',
    price: 32000,
    material: 'Teak Wood',
    description: 'Traditional South Indian settee with ornate floral carvings on the backrest and slatted seat. A timeless piece that blends craftsmanship with everyday comfort.',
    dimensions: 'L: 190cm  W: 70cm  H: 100cm',
    warranty: '2 Years',
    image: 'images/IMG-20251006-WA0013.jpg',
    rating: 4.6,
    featured: false
  },
  {
    id: 4,
    name: 'Yellow Cushion Sofa Set (3+1+1+Table)',
    category: 'sofa',
    price: 55000,
    material: 'Hardwood with Fabric Cushions',
    description: '5-piece sofa set with yellow velvet cushions — includes a 3-seater, two single-seaters and a centre coffee table. Dark hardwood frame with modern upholstery.',
    dimensions: '3-seater: L: 185cm  Singles: 80cm each',
    warranty: '2 Years',
    image: 'images/IMG-20251114-WA0008.jpg',
    rating: 4.7,
    featured: true
  },
  {
    id: 5,
    name: 'Carved Teak 3-Seater Bench',
    category: 'sofa',
    price: 30000,
    material: 'Teak Wood',
    description: 'Solid teak 3-seater bench with ornate carved backrest panels. Slatted seat for natural ventilation. Ideal for both indoor and covered outdoor spaces.',
    dimensions: 'L: 185cm  W: 68cm  H: 92cm',
    warranty: '2 Years',
    image: 'images/IMG-20251114-WA0016.jpg',
    rating: 4.5,
    featured: false
  },
  {
    id: 6,
    name: 'Storage Sofa Bench with Drawers',
    category: 'sofa',
    price: 35000,
    material: 'Teak Wood',
    description: 'Multi-functional diwan with built-in front drawer storage. Intricate lattice and floral carvings on the backrest. A smart combination of style and utility.',
    dimensions: 'L: 188cm  W: 72cm  H: 95cm',
    warranty: '3 Years',
    image: 'images/IMG-20251114-WA0024.jpg',
    rating: 4.7,
    featured: false
  },
  {
    id: 7,
    name: 'Bamboo Cane Sofa Set (3+1+1+Table)',
    category: 'sofa',
    price: 42000,
    material: 'Bamboo & Cane',
    description: 'Eco-friendly bamboo and cane sofa set with traditional woven cushion pads. Complete 5-piece set with centre table. Lightweight, durable and naturally ventilated.',
    dimensions: '3-seater: L: 178cm  Singles: 76cm each',
    warranty: '1 Year',
    image: 'images/IMG-20251206-WA0002.jpg',
    rating: 4.3,
    featured: false
  },
  {
    id: 8,
    name: 'Carved Teak Single Arm Chair Sofa',
    category: 'sofa',
    price: 18000,
    material: 'Teak Wood',
    description: 'Compact single-seater with carved backrest and armrests. Features a slatted seat with ornate carvings. Pairs well with any diwan or sofa set.',
    dimensions: 'W: 78cm  D: 68cm  H: 96cm',
    warranty: '2 Years',
    image: 'images/IMG-20251206-WA0004.jpg',
    rating: 4.4,
    featured: false
  },
  {
    id: 9,
    name: 'Woven Teak 3-Seater Diwan',
    category: 'sofa',
    price: 34000,
    material: 'Teak Wood',
    description: 'Elegant teak diwan featuring a combination of ornate carved top rail, woven cane panels and slatted seat. A unique fusion of traditional styles.',
    dimensions: 'L: 192cm  W: 74cm  H: 98cm',
    warranty: '2 Years',
    image: 'images/IMG-20251220-WA0006.jpg',
    rating: 4.6,
    featured: false
  },
  {
    id: 10,
    name: 'Dark Rosewood 3-Seater Bench',
    category: 'sofa',
    price: 36000,
    material: 'Rosewood',
    description: 'Stately rosewood bench with spindle back panels and carved medallion details. Deep dark finish with natural wood grain. Built to last generations.',
    dimensions: 'L: 196cm  W: 72cm  H: 96cm',
    warranty: '3 Years',
    image: 'images/IMG-20251221-WA0004.jpg',
    rating: 4.7,
    featured: false
  },
  {
    id: 11,
    name: 'Spindle Back Rosewood Diwan',
    category: 'sofa',
    price: 33000,
    material: 'Rosewood',
    description: 'Classic rosewood diwan with turned spindle back rail and intricately carved central panel. Brass side medallions add a premium touch.',
    dimensions: 'L: 194cm  W: 74cm  H: 94cm',
    warranty: '3 Years',
    image: 'images/IMG-20251224-WA0010.jpg',
    rating: 4.5,
    featured: false
  },
  {
    id: 12,
    name: 'Royal Blue Velvet Chaise Lounge',
    category: 'sofa',
    price: 45000,
    material: 'Teak Wood with Velvet Upholstery',
    description: 'Luxurious chaise lounge with royal blue velvet upholstery on a solid teak base. Curved backrest and elegant scroll arms. A statement piece for premium interiors.',
    dimensions: 'L: 175cm  W: 65cm  H: 78cm',
    warranty: '2 Years',
    image: 'images/IMG-20251224-WA0011.jpg',
    rating: 4.8,
    featured: true
  },
  {
    id: 13,
    name: 'Ornate Carved Teak 3-Seater',
    category: 'sofa',
    price: 38000,
    material: 'Teak Wood',
    description: 'Heavily carved teak 3-seater with three ornate backrest panels and decorative spindle sides. Premium natural teak finish. A masterpiece of South Indian carpentry.',
    dimensions: 'L: 198cm  W: 76cm  H: 100cm',
    warranty: '3 Years',
    image: 'images/IMG-20260306-WA0012.jpg',
    rating: 4.9,
    featured: false
  },
  {
    id: 14,
    name: 'Medallion Carved Rosewood Bench',
    category: 'sofa',
    price: 40000,
    material: 'Rosewood',
    description: 'Premium rosewood bench with three carved circular medallion panels in the backrest. Slatted seat, turned legs and armrests. Rich two-tone finish.',
    dimensions: 'L: 200cm  W: 74cm  H: 97cm',
    warranty: '3 Years',
    image: 'images/IMG-20260306-WA0013.jpg',
    rating: 4.8,
    featured: false
  },
  {
    id: 15,
    name: 'Premium Carved Teak Settee',
    category: 'sofa',
    price: 36000,
    material: 'Teak Wood',
    description: 'Traditional settee with finely carved top rail and three decorative backrest panels. The balanced design with slatted seat makes it ideal for any living space.',
    dimensions: 'L: 190cm  W: 70cm  H: 96cm',
    warranty: '2 Years',
    image: 'images/IMG-20260413-WA0008.jpg',
    rating: 4.6,
    featured: false
  },
  {
    id: 16,
    name: 'Curved Mint Cushion Sofa',
    category: 'sofa',
    price: 48000,
    material: 'Teak Wood with Fabric Cushions',
    description: 'Contemporary curved sofa with mint green cushion fabric on a solid teak frame. Scroll armrests and artistic slatted back give it a distinctive character.',
    dimensions: 'L: 180cm  W: 72cm  H: 90cm',
    warranty: '2 Years',
    image: 'images/IMG-20260413-WA0009.jpg',
    rating: 4.7,
    featured: false
  },
  {
    id: 17,
    name: 'Panel Back Teak 3-Seater',
    category: 'sofa',
    price: 32000,
    material: 'Teak Wood',
    description: 'Clean-lined teak 3-seater with carved raised panel backrest and slatted seat. Solid construction with a warm natural teak finish. Versatile and timeless.',
    dimensions: 'L: 192cm  W: 72cm  H: 95cm',
    warranty: '2 Years',
    image: 'images/IMG-20260413-WA0012.jpg',
    rating: 4.5,
    featured: false
  },

  /* ────────────── BEDS ────────────── */
  {
    id: 18,
    name: 'Teak Bed with Padded Headboard + Side Table',
    category: 'bed',
    price: 42000,
    material: 'Teak Wood with Leatherette Padding',
    description: 'Solid teak double bed with a padded fabric headboard accented with crystal studs. Comes with a matching teak side table featuring a drawer and cabinet.',
    dimensions: 'King: 200cm × 180cm  Height: 50cm',
    warranty: '3 Years',
    image: 'images/IMG-20250925-WA0002.jpg',
    rating: 4.7,
    featured: true
  },
  {
    id: 19,
    name: 'Carved Teak Double Bed',
    category: 'bed',
    price: 35000,
    material: 'Teak Wood',
    description: 'Elegant teak double bed with intricately carved headboard and footboard. Turned bedposts and detailed floral motifs make this a showpiece for your bedroom.',
    dimensions: 'Queen: 198cm × 160cm  Height: 48cm',
    warranty: '3 Years',
    image: 'images/IMG-20250928-WA0004.jpg',
    rating: 4.6,
    featured: false
  },
  {
    id: 20,
    name: 'Wide Carved Teak Bed',
    category: 'bed',
    price: 40000,
    material: 'Teak Wood',
    description: 'Spacious teak bed with an arched carved headboard. Solid construction with wide plank base and turned corner posts. A classic choice for master bedrooms.',
    dimensions: 'King: 210cm × 180cm  Height: 50cm',
    warranty: '3 Years',
    image: 'images/IMG-20251008-WA0002.jpg',
    rating: 4.5,
    featured: false
  },
  {
    id: 21,
    name: 'Teak Bed with Navy Tufted Headboard',
    category: 'bed',
    price: 38000,
    material: 'Teak Wood with Leatherette',
    description: 'Modern solid teak bed with a tall navy blue tufted leatherette headboard decorated with diamond-pattern crystal buttons. Clean lines and contemporary styling.',
    dimensions: 'King: 200cm × 180cm  Height: 52cm',
    warranty: '3 Years',
    image: 'images/IMG-20251224-WA0001.jpg',
    rating: 4.8,
    featured: false
  },
  {
    id: 22,
    name: 'King Size Bed Set with Side Tables',
    category: 'bed',
    price: 65000,
    material: 'Teak Wood with Leatherette',
    description: 'Complete bedroom set — king size teak bed with tufted blue headboard, two matching side tables with drawers. Perfect for a luxury bedroom upgrade.',
    dimensions: 'King: 215cm × 185cm  Side tables: 50cm × 45cm',
    warranty: '3 Years',
    image: 'images/IMG-20251224-WA0012.jpg',
    rating: 4.9,
    featured: true
  },
  {
    id: 23,
    name: 'Simple Teak Single Bed',
    category: 'bed',
    price: 18000,
    material: 'Teak Wood',
    description: 'Sturdy and simple teak single bed with a light carved headboard. Ideal for children\'s rooms or guest bedrooms. Clean design with excellent build quality.',
    dimensions: 'Single: 198cm × 90cm  Height: 40cm',
    warranty: '2 Years',
    image: 'images/IMG-20251224-WA0016.jpg',
    rating: 4.3,
    featured: false
  },
  {
    id: 24,
    name: 'Ornate Carved Teak Double Bed',
    category: 'bed',
    price: 48000,
    material: 'Teak Wood',
    description: 'Highly ornate teak double bed with deeply carved floral and vine motifs across the headboard and footboard. Turned spindle side rails. A true heirloom piece.',
    dimensions: 'Queen: 198cm × 160cm  Height: 52cm',
    warranty: '5 Years',
    image: 'images/IMG-20251224-WA0017.jpg',
    rating: 4.9,
    featured: false
  },
  {
    id: 25,
    name: 'Classic Teak Double Bed',
    category: 'bed',
    price: 32000,
    material: 'Teak Wood',
    description: 'Well-proportioned teak double bed with a carved sunburst headboard. Spindle side rails and sturdy corner posts. Excellent finish and durability.',
    dimensions: 'Queen: 198cm × 162cm  Height: 46cm',
    warranty: '3 Years',
    image: 'images/IMG-20260206-WA0004.jpg',
    rating: 4.5,
    featured: false
  },
  {
    id: 26,
    name: 'Teak Bed with Storage Drawer',
    category: 'bed',
    price: 45000,
    material: 'Teak Wood with Leatherette',
    description: 'Practical and stylish teak bed with a dark tufted headboard and a built-in front storage drawer. Combines bedroom elegance with smart storage.',
    dimensions: 'King: 205cm × 180cm  Height: 52cm',
    warranty: '3 Years',
    image: 'images/IMG-20260206-WA0005.jpg',
    rating: 4.7,
    featured: false
  },
  {
    id: 27,
    name: 'Carved Floral Teak Double Bed',
    category: 'bed',
    price: 38000,
    material: 'Teak Wood',
    description: 'Beautiful teak bed with a carved floral vine headboard and matching footboard. Spindle rails add elegance. Ideal for traditional and transitional interiors.',
    dimensions: 'Queen: 198cm × 160cm  Height: 50cm',
    warranty: '3 Years',
    image: 'images/IMG-20260206-WA0006.jpg',
    rating: 4.6,
    featured: false
  },
  {
    id: 28,
    name: 'Compact Dark Wood Single Bed',
    category: 'bed',
    price: 22000,
    material: 'Hardwood',
    description: 'Neat and compact single bed with slatted head and footboards in dark hardwood finish. Mission-style design with clean horizontal lines. Easy assembly.',
    dimensions: 'Single: 195cm × 90cm  Height: 44cm',
    warranty: '2 Years',
    image: 'images/IMG-20260206-WA0007.jpg',
    rating: 4.3,
    featured: false
  },
  {
    id: 29,
    name: 'Simple Teak Light Finish Bed',
    category: 'bed',
    price: 20000,
    material: 'Teak Wood',
    description: 'Simple single bed in light teak finish with a minimally carved headboard. Clean, no-fuss design that works well in any bedroom setting.',
    dimensions: 'Single: 198cm × 90cm  Height: 40cm',
    warranty: '2 Years',
    image: 'images/IMG-20260206-WA0008.jpg',
    rating: 4.2,
    featured: false
  },
  {
    id: 30,
    name: 'Teak Spindle Single Bed',
    category: 'bed',
    price: 19000,
    material: 'Teak Wood',
    description: 'Charming single bed with a turned spindle headboard in natural teak. Sturdy slatted base with turned corner posts. Ideal for children or guest rooms.',
    dimensions: 'Single: 195cm × 90cm  Height: 44cm',
    warranty: '2 Years',
    image: 'images/IMG-20260413-WA0007.jpg',
    rating: 4.4,
    featured: false
  },

  /* ────────────── WARDROBES ────────────── */
  {
    id: 31,
    name: 'Single Door Carved Almirah',
    category: 'wardrobe',
    price: 28000,
    material: 'Rosewood',
    description: 'Tall single-door almirah with deeply carved floral and vine motifs on the door panels and pilasters. Dark rosewood finish. Perfect for smaller spaces.',
    dimensions: 'W: 75cm  D: 48cm  H: 195cm',
    warranty: '3 Years',
    image: 'images/IMG-20251011-WA0000.jpg',
    rating: 4.6,
    featured: false
  },
  {
    id: 32,
    name: 'Double Door Ornate Teak Wardrobe',
    category: 'wardrobe',
    price: 55000,
    material: 'Teak Wood',
    description: 'Majestic double-door teak wardrobe with carved pillars, arched panels and elaborate top cornice. Multi-shelf interior with hanging space. A grand bedroom statement.',
    dimensions: 'W: 140cm  D: 55cm  H: 210cm',
    warranty: '5 Years',
    image: 'images/IMG-20251011-WA0001.jpg',
    rating: 4.9,
    featured: true
  },
  {
    id: 33,
    name: 'Floral 2-Door Carved Wardrobe',
    category: 'wardrobe',
    price: 32000,
    material: 'Teak Wood',
    description: 'Two-door wardrobe with intricate floral carvings on each door panel — elephant motif on one, grapevine on the other. Brass door handles. Warm teak finish.',
    dimensions: 'W: 110cm  D: 50cm  H: 185cm',
    warranty: '3 Years',
    image: 'images/IMG-20251011-WA0003.jpg',
    rating: 4.7,
    featured: false
  },
  {
    id: 34,
    name: 'Single Carved Door Wardrobe',
    category: 'wardrobe',
    price: 30000,
    material: 'Teak Wood',
    description: 'Practical single large-door wardrobe with a carved door and decorative top drawer. Includes storage shelves and hanging rail. Classic South Indian almirah style.',
    dimensions: 'W: 85cm  D: 50cm  H: 190cm',
    warranty: '3 Years',
    image: 'images/IMG-20251011-WA0004.jpg',
    rating: 4.5,
    featured: false
  },
  {
    id: 35,
    name: 'Twisted Column 2-Door Wardrobe',
    category: 'wardrobe',
    price: 48000,
    material: 'Teak Wood',
    description: 'Distinguished two-door wardrobe with tall twisted rope-carved columns flanking carved door panels. Ornate top cornice. A premium showpiece for master bedrooms.',
    dimensions: 'W: 130cm  D: 55cm  H: 205cm',
    warranty: '5 Years',
    image: 'images/IMG-20251011-WA0005.jpg',
    rating: 4.8,
    featured: false
  },
  {
    id: 36,
    name: 'Premium Gold Finish Royal Wardrobe',
    category: 'wardrobe',
    price: 75000,
    material: 'Teak Wood with Gold Polish',
    description: 'The crown jewel of our wardrobe collection. This two-door wardrobe features elaborate lattice and floral carvings with a premium gold-tinted polish and ornate top crown.',
    dimensions: 'W: 145cm  D: 58cm  H: 215cm',
    warranty: '5 Years',
    image: 'images/IMG-20251011-WA0006.jpg',
    rating: 5.0,
    featured: true
  },
  {
    id: 37,
    name: 'Figurine Carved Rosewood Wardrobe',
    category: 'wardrobe',
    price: 52000,
    material: 'Rosewood',
    description: 'Majestic rosewood wardrobe with full-length human figurine carvings on both door panels. Fluted twisted columns and deep cornice. Dark mahogany finish.',
    dimensions: 'W: 138cm  D: 55cm  H: 208cm',
    warranty: '5 Years',
    image: 'images/IMG-20251011-WA0007.jpg',
    rating: 4.9,
    featured: false
  },

  /* ────────────── DOORS ────────────── */
  {
    id: 38,
    name: 'Pooja Room Double Door – Vaazha Valamudan',
    category: 'door',
    price: 35000,
    material: 'Teak Wood',
    description: 'Auspicious pooja room entrance door with Tamil inscription "வாழ்க வளமுடன்" (Live with Abundance). Features carved human figurines, floral motifs and decorative columns.',
    dimensions: 'W: 110cm  H: 200cm (with frame)',
    warranty: '5 Years',
    image: 'images/IMG-20251011-WA0009.jpg',
    rating: 4.9,
    featured: false
  },
  {
    id: 39,
    name: 'Main Entrance Double Door with Carved Frame',
    category: 'door',
    price: 65000,
    material: 'Teak Wood',
    description: 'Grand main entrance double door with an elaborately carved surround frame featuring peacocks, vines and floral motifs. Premium quality finish and solid brass hardware.',
    dimensions: 'W: 140cm  H: 230cm (including frame)',
    warranty: '5 Years',
    image: 'images/IMG-20260410-WA0002.jpg',
    rating: 5.0,
    featured: true
  },
  {
    id: 40,
    name: 'Deity Carved Single Door with Frame',
    category: 'door',
    price: 42000,
    material: 'Teak Wood',
    description: 'Single door with intricate deity and peacock carvings on the full panel. Decorative carved frame with Ganesha motif on the top rail. Ideal for pooja rooms or main entrance.',
    dimensions: 'W: 90cm  H: 215cm (including frame)',
    warranty: '5 Years',
    image: 'images/IMG-20260410-WA0006.jpg',
    rating: 4.8,
    featured: false
  },

  /* ────────────── DINING TABLES ────────────── */
  {
    id: 41,
    name: '4-Seater Teak Square Table + Stools',
    category: 'dining',
    price: 22000,
    material: 'Teak Wood',
    description: 'Compact 4-seater dining set with a polished teak square tabletop and four matching stools. Simple, sturdy design perfect for small families and compact dining areas.',
    dimensions: 'Table: 90cm × 90cm  H: 75cm  Stools: 35cm × 35cm',
    warranty: '2 Years',
    image: 'images/IMG-20251019-WA0002.jpg',
    rating: 4.4,
    featured: false
  },
  {
    id: 42,
    name: '6-Seater Glass Top Dining Set',
    category: 'dining',
    price: 48000,
    material: 'Teak Wood with Glass Top',
    description: 'Elegant 6-seater dining set with a glass top table on a solid teak frame. Six matching dark wood chairs with slatted backs. A sophisticated choice for formal dining rooms.',
    dimensions: 'Table: 150cm × 80cm  H: 76cm',
    warranty: '2 Years',
    image: 'images/IMG-20251224-WA0003.jpg',
    rating: 4.7,
    featured: true
  },
  {
    id: 43,
    name: '4-Seater Teak Table + Bench Set',
    category: 'dining',
    price: 24000,
    material: 'Teak Wood',
    description: 'Classic 4-seater dining set with a solid teak table and two long benches. Live-edge inspired tabletop with a glossy finish. Great for casual family dining.',
    dimensions: 'Table: 100cm × 80cm  H: 76cm  Benches: 100cm long',
    warranty: '2 Years',
    image: 'images/IMG-20251224-WA0004.jpg',
    rating: 4.5,
    featured: false
  },
  {
    id: 44,
    name: '4-Seater Marble Top Dining Set',
    category: 'dining',
    price: 38000,
    material: 'Teak Wood with Marble Top',
    description: '4-seater dining set with a faux marble ceramic top on a carved teak frame. Four matching chairs with carved backs and burgundy cushion seats. Elegant and easy to clean.',
    dimensions: 'Table: 120cm × 75cm  H: 76cm',
    warranty: '2 Years',
    image: 'images/IMG-20251224-WA0019.jpg',
    rating: 4.6,
    featured: false
  },
  {
    id: 45,
    name: 'Round Glass Top Dining Table (4-Seater)',
    category: 'dining',
    price: 42000,
    material: 'Rosewood with Glass Top',
    description: 'Stunning round glass top dining table on a pedestal rosewood base with cabriole legs. Four matching upholstered chairs with cream seat pads.',
    dimensions: 'Table: Ø 110cm  H: 76cm',
    warranty: '2 Years',
    image: 'images/IMG-20251224-WA0020.jpg',
    rating: 4.7,
    featured: false
  },
  {
    id: 46,
    name: '4-Seater Glass Top with Carved Chairs',
    category: 'dining',
    price: 36000,
    material: 'Teak Wood with Glass Top',
    description: '4-seater dining set with rectangular glass top and solid teak base. Four ornate carved chairs with burgundy leatherette cushion seats.',
    dimensions: 'Table: 120cm × 70cm  H: 76cm',
    warranty: '2 Years',
    image: 'images/IMG-20260413-WA0015.jpg',
    rating: 4.5,
    featured: false
  },

  /* ────────────── CHAIRS ────────────── */
  {
    id: 47,
    name: 'Carved Reception Chair Set (10-Piece)',
    category: 'chair',
    price: 85000,
    material: 'Teak Wood with Leatherette',
    description: 'Premium set of 10 carved teak chairs with cream leatherette cushioned seats and backs. Ornate carved crest rails and cabriole legs. Ideal for wedding halls or grand homes.',
    dimensions: 'Per chair: W: 55cm  D: 50cm  H: 100cm',
    warranty: '3 Years',
    image: 'images/IMG-20251224-WA0009.jpg',
    rating: 4.8,
    featured: true
  },
  {
    id: 48,
    name: 'Dark Cushion Dining Chairs (Set of 4)',
    category: 'chair',
    price: 18000,
    material: 'Hardwood with Leatherette',
    description: 'Set of 4 high-back dining chairs with dark leatherette upholstery and hardwood frame. Elegant vertical slat backrest design. Perfect for modern dining rooms.',
    dimensions: 'Per chair: W: 46cm  D: 48cm  H: 100cm',
    warranty: '2 Years',
    image: 'images/IMG-20251224-WA0018.jpg',
    rating: 4.4,
    featured: false
  },
  {
    id: 49,
    name: 'Teak Rocking Chair',
    category: 'chair',
    price: 12000,
    material: 'Teak Wood',
    description: 'Classic teak rocking chair with slatted seat and backrest. Wide curved armrests and smooth rocking arc. Great for verandahs, reading nooks, and relaxation.',
    dimensions: 'W: 60cm  D: 85cm  H: 100cm',
    warranty: '2 Years',
    image: 'images/IMG-20260306-WA0009.jpg',
    rating: 4.6,
    featured: false
  },
  {
    id: 50,
    name: 'Teak Easy Lounge Chair',
    category: 'chair',
    price: 14000,
    material: 'Teak Wood',
    description: 'Comfortable easy lounge chair with a slatted reclined backrest and wide flat armrests. Solid teak construction with a warm honey finish. Perfect for relaxing.',
    dimensions: 'W: 62cm  D: 80cm  H: 96cm',
    warranty: '2 Years',
    image: 'images/IMG-20260413-WA0010.jpg',
    rating: 4.5,
    featured: false
  },
  {
    id: 51,
    name: 'Traditional Wooden Rocking Chair',
    category: 'chair',
    price: 15000,
    material: 'Teak Wood',
    description: 'Ornate traditional rocking chair with an intricately carved backrest medallion, spoke wheels and slatted seat. A blend of functionality and artistry.',
    dimensions: 'W: 62cm  D: 90cm  H: 105cm',
    warranty: '2 Years',
    image: 'images/IMG-20260413-WA0018.jpg',
    rating: 4.7,
    featured: false
  },

  /* ────────────── BABY CRADLES & SWINGS ────────────── */
  {
    id: 52,
    name: 'Carved Teak Baby Cradle',
    category: 'cradle',
    price: 18000,
    material: 'Teak Wood',
    description: 'Beautifully carved teak baby cradle with deeply detailed floral headboard carving. Smooth rocking motion, safe spindle sides and durable brass chain hooks.',
    dimensions: 'L: 90cm  W: 45cm  H: 60cm (excluding chain)',
    warranty: '2 Years',
    image: 'images/IMG-20251023-WA0000.jpg',
    rating: 4.8,
    featured: false
  },
  {
    id: 53,
    name: 'Baby Cradle Frame Set',
    category: 'cradle',
    price: 12000,
    material: 'Teak Wood & Rosewood',
    description: 'Set of baby cradle frames available in teak and rosewood. Lightweight yet sturdy with safe brass hanging fixtures. Easy to assemble and detach.',
    dimensions: 'L: 85cm  W: 40cm',
    warranty: '2 Years',
    image: 'images/IMG-20251110-WA0004.jpg',
    rating: 4.4,
    featured: false
  },
  {
    id: 54,
    name: 'Indoor Hanging Jhula with Carved Frame',
    category: 'cradle',
    price: 55000,
    material: 'Teak Wood',
    description: 'Grand indoor wall-mounted jhula (swing) with an elaborately carved overhead arch frame featuring peacock and floral motifs. Includes rope chains and cushioned seat.',
    dimensions: 'Frame: W: 150cm  H: 220cm  Seat: L: 120cm',
    warranty: '3 Years',
    image: 'images/IMG-20260413-WA0011.jpg',
    rating: 4.9,
    featured: true
  },
  {
    id: 55,
    name: 'Outdoor Garden Swing with A-Frame',
    category: 'cradle',
    price: 32000,
    material: 'Teak Wood',
    description: 'Sturdy outdoor garden swing with a self-standing A-frame structure. Carved column supports and a wide plank seat with chain suspension. Ideal for gardens and terraces.',
    dimensions: 'Frame: W: 220cm  D: 130cm  H: 200cm  Seat: L: 150cm',
    warranty: '3 Years',
    image: 'images/IMG-20260413-WA0016.jpg',
    rating: 4.7,
    featured: false
  },

  /* ────────────── POOJA ITEMS ────────────── */
  {
    id: 56,
    name: 'Teak Pooja Peetam / Prayer Bench',
    category: 'pooja',
    price: 5500,
    material: 'Teak Wood',
    description: 'Simple yet solid teak peetam for pooja rituals. Flat top surface ideal for placing deity idols, lamps or offerings. Smooth finish with low-rise legs.',
    dimensions: 'L: 60cm  W: 30cm  H: 18cm',
    warranty: '1 Year',
    image: 'images/IMG-20251019-WA0005.jpg',
    rating: 4.5,
    featured: false
  },
  {
    id: 57,
    name: 'Teak Deepam / Lamp Stand',
    category: 'pooja',
    price: 8500,
    material: 'Teak Wood with Glass',
    description: 'Elegant teak lamp stand with glass-enclosed lantern cabinet on carved cabriole legs. Protects the flame from wind while adding a decorative touch to any pooja space.',
    dimensions: 'W: 25cm  D: 25cm  H: 75cm',
    warranty: '1 Year',
    image: 'images/IMG-20251224-WA0014.jpg',
    rating: 4.7,
    featured: true
  },
  {
    id: 58,
    name: 'Carved Pooja Platform with Border',
    category: 'pooja',
    price: 7000,
    material: 'Teak Wood',
    description: 'Premium teak pooja peetam with a carved scallop-shell border along all four sides. Smooth top surface, low profile and excellent craftsmanship.',
    dimensions: 'L: 75cm  W: 35cm  H: 15cm',
    warranty: '1 Year',
    image: 'images/IMG-20251226-WA0004.jpg',
    rating: 4.6,
    featured: false
  },
  {
    id: 59,
    name: 'Teak Peetam – Medium',
    category: 'pooja',
    price: 4500,
    material: 'Teak Wood',
    description: 'Medium-sized solid teak peetam with a clean polished top. Traditional short-leg design used in pooja rooms and religious ceremonies.',
    dimensions: 'L: 50cm  W: 28cm  H: 14cm',
    warranty: '1 Year',
    image: 'images/IMG-20251226-WA0005.jpg',
    rating: 4.4,
    featured: false
  },
  {
    id: 60,
    name: 'Simple Teak Square Peetam',
    category: 'pooja',
    price: 3500,
    material: 'Teak Wood',
    description: 'Small square teak peetam with a polished top and short sturdy legs. A versatile piece used in pooja rooms, temples and home altars.',
    dimensions: 'L: 40cm  W: 40cm  H: 12cm',
    warranty: '1 Year',
    image: 'images/IMG-20251226-WA0006.jpg',
    rating: 4.3,
    featured: false
  },

  /* ────────────── DECORATIVES ────────────── */
  {
    id: 61,
    name: 'Hamsa Bird Carved Round Stool',
    category: 'decorative',
    price: 6500,
    material: 'Hardwood',
    description: 'Unique round stool with a deeply carved Hamsa (swan) bird motif on the seat top. Dark antique finish with sturdy short legs. A beautiful decorative accent piece.',
    dimensions: 'Dia: 38cm  H: 35cm',
    warranty: '1 Year',
    image: 'images/IMG-20251206-WA0011.jpg',
    rating: 4.6,
    featured: false
  },
  {
    id: 62,
    name: 'Elephant Parade Decorative Panel',
    category: 'decorative',
    price: 9500,
    material: 'Teak Wood',
    description: 'Carved teak wall panel or furniture headpiece featuring a procession of seven elephants in relief. Rich natural teak finish. Perfect for wall décor or as a bed headboard accent.',
    dimensions: 'L: 120cm  H: 25cm  D: 4cm',
    warranty: '1 Year',
    image: 'images/IMG-20260328-WA0010.jpg',
    rating: 4.8,
    featured: false
  },
];
